### PR TITLE
Add diffuse template

### PR DESCRIPTION
**Pull request by forivall**
Note: this was written a while ago (late 2012), so some newer languages might be
missing

### CODE REVIEW

**Comment by xHN35RQ** [comment]
Thanks for your pull request! I'll look through this and your other pulls. However I'm not decided yet on the appropriate action, whether I should accept these improvements, or keep my branch as a maintenance-only branch. [There is discussion of re-organizing](https://github.com/chriskempson/base16-builder/issues/293) the base16 family of color templates, so I may wait a bit on your pulls depending on how things move forward.

Thanks!

**Comment by xHN35RQ** [comment]
I'm going to merge this in, but what is diffuse? Is it this? http://diffuse.sourceforge.net/index.html

**Comment by forivall** [comment]
Yes, that's exactly it; it's my preferred merge tool.

**Comment by xHN35RQ** [comment]
> Yes, that's exactly it; it's my preferred merge tool.

Nice, thanks for adding the template!

**Comment by xHN35RQ** [comment]
@forivall have you used [meld](http://meldmerge.org) and if so, how does diffuse compare? Thanks.

**Comment by forivall** [comment]
Meld compacts the empty space where there aren't common lines, diffuse leaves empty space where there aren't common lines. Meld also tries to be smarter, but, in my experience it's more annoying than useful. Hopefully that makes sense. Otherwise, screenshots!

diffuse
2015-09-21-diffuse-example
2015-09-21-diffuse2-example

meld
2015-09-21-meld-example
2015-09-21-meld2-example

**Comment by xHN35RQ** [comment]
Ah very handy, thank you for the screenshots! :+1:

**Pull request merged**
