### PR TITLE
Fix mix function

### PR DESCRIPTION
**Pull request by forivall**
The mix function is currently broken. Let me know if I should include tests with this. I'm not a rubyist, so someone else would need to set up the tests / framework, and I'll include my test in the correct location.

### CODE REVIEW

**Comment by xHN35RQ** [comment]
I'll try to test this locally when I get a chance, although I'm not much of a rubyist either.

**Comment by forivall** [comment]
I just remembered why this made sense: the original removal of alpha channel from the calculation assumed that alpha was set to zero, and made some other mistakes. I went back to the origin, and simplified the equation for both alphas being equal to 1, and this is how it results when that simplification is done. I might upload an image of some handwritten algebra just for fun :smile:.

**Comment by xHN35RQ** [comment]
I am thinking this and #7 should not be merged at the present time without the testing which I don't have the experience to do. They represent a significant change in the build script, and I feel more comfortable keeping my branch cosmetic/maintenance changes. I hope we can get some momentum with a base16 org and move your changes to a base16-ruby development branch.

These are my thoughts at the moment, however let me know your thoughts, as perhaps I'm missing something here. Thanks!

**Comment by xHN35RQ** [comment]
@forivall for some reason running `./base16` goes into an infinite loop, restarting immediately after completing a build. Other than that, the changes you made seem to be producing identical templates as the old mix function. So far, so good.

**Comment by xHN35RQ** [comment]
Ok I'm seeing differences in Matlab and Roxterm themes. I'm not sure if this is an improvement, or not. Here's some examples comparing 1417de7da5bdc4cf3afd4aabcd2923b2f092db4b against dfe4cbbf7941ee13ddd9890e74e8787e16375dff:

* https://gist.github.com/xHN35RQ/5e2497432a4e1009d00b/revisions?diff=split
* https://gist.github.com/xHN35RQ/74bf8837dc8f6eee5478/revisions?diff=split
* https://gist.github.com/xHN35RQ/e0336e7a725250e65eee/revisions?diff=split
* https://gist.github.com/xHN35RQ/e896a644a992969023f8/revisions?diff=split

I noticed that before your fix, roxterm templates had some colors as 

```
-8=#..fea4..fea4..fe95..fe95..fe8e..fe8e
-9=#b1b1..fefe..fefe..fede..fede
-10=#..fe90..fe902222..f5b..f5b
```
Is this valid for roxterm? Your fix updates those same lines to 

```
+8=#20201b1b1818
+9=#dddd41413535
+10=#1919aaaa6262
```

**Comment by forivall** [comment]
Exactly, before the fix, they're invalid, because the broken mix function can output colours with r, g or b greater than 255 or less than 0.
mix_fix

**Comment by xHN35RQ** [comment]
Ah, I thought as much. Thanks for confirming, and for taking the time to make this fix. I'll merge your changes. Thanks for your patience as I worked through testing your changes. :+1:

**Pull request merged**
