### PR TITLE
[mutt] Update dark theme

### PR DESCRIPTION
**Pull request by pickfire**
I have added support for smileys and some others add on for dark theme. Some addition update will be coming soon.

2015-09-21-225835_564x340_scrot
2015-09-21-225901_564x340_scrot
2015-09-21-230001_564x340_scrot

### CODE REVIEW

**Comment by xHN35RQ** [comment]
Thanks for the pull request. I'm not able to compare your changes against the existing mutt template, since I don't use mutt myself. Please elaborate on the changes you referred to "some others add on for dark theme" - thanks!

> Some addition update will be coming soon.

Will you push these updates to this pull request?

**Comment by pickfire** [comment]
It seems that I have problem building the solarized scheme when I `./base16 schemes/solarized.yml`, it turn out to be **brewer** theme instead of **solarized**.

There are too many changes, In My Humble Opinion, I don't think I have the time to lists all that out. Sorry that I can just show you the original image.

*In a nutshell*, I had just make it **more readable**, here is the image of the original color:

2015-09-22-181239_564x340_scrot
2015-09-22-181252_564x340_scrot
2015-09-22-181307_564x340_scrot

**Comment by xHN35RQ** [comment]
Thanks for the photos, that helps to see the differences.

So you're saying that this file is not the solarized theme? https://github.com/xHN35RQ/base16-builder/blob/master/schemes/solarized.yml

**Comment by pickfire** [comment]
Sorry, I have typo error so that is why it doesn't work, I did `./base16 schemes/solarized.yml` instead of `./base16 -s schemes/solarized.yml`.

**Comment by xHN35RQ** [comment]
@pickfire Perhaps some people like the original coloring... so let's do this. Let's call your version `mutt-alt` and put your templates into `templates/mutt-alt` then rebase your pull request so the commit is updated with these changes.

This way we can have both options available: your version and the original version. Thanks!

**Comment by pickfire** [comment]
I am not sure what you mean and I doesn't know `git rebase` very well, I guess I will just push another commit.

**Comment by pickfire** [comment]
Well, I guess I just did `git rebase`.

**Comment by xHN35RQ** [comment]
Right, but you have to rebase onto a specific commit otherwise you introduce a lot of extra commits. I'm trying to keep the commit stream as clean as possible.

So don't worry about it for now, I'll cherry-pick 248b221 directly into the master.

**Comment by pickfire** [comment]
I heard about cherry-pick but how do you use it?

**Comment by xHN35RQ** [comment]
Here's a start https://stackoverflow.com/questions/1241720/git-cherry-pick-vs-merge-workflow

**Comment by pickfire** [comment]
Thanks.

**Comment by xHN35RQ** [comment]
Can you please give me a single commit with just adding ` templates/mutt-alt/light.256.muttrc.erb` and `templates/mutt-alt/dark.256.muttrc.erb`

this commit has an extra file change of `templates/mutt/dark.256.muttrc.erb` https://github.com/pickfire/base16-builder/commit/248b221277b5de9d992b80f08391a806ae9943e7

Thanks

**Comment by xHN35RQ** [comment]
I added your templates to `templates/mutt` but renamed them to `alt` in 30feb91a4ca6f5c5f4461dda878fd1adcc103eb1

Thanks!

**Pull request closed without merging**
